platform :ios, '8.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'EaseMobLiveDemo' do
pod 'HyphenateLite'
pod 'Masonry'
pod 'EaseUILite', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
pod 'AFNetworking', '~> 3.1.0'

end
